run:
  # Timeout for the whole linters run
  timeout: 5m

  # Number of CPUs to use (0 = auto)
  concurrency: 0

  # Allow issues from test files
  tests: true

linters:
  # Disable all linters by default, then enable specific ones
  disable-all: true
  enable:
    # Most important - detects critical issues
    - govet         # Analyze code to find latent bugs
    - errcheck      # Check for unchecked errors
    - staticcheck   # Analyze code for common mistakes

    # Code quality basic
    - gosimple      # Simplify code
    - ineffassign   # Detect ineffectual assignments
    - unused        # Find unused code

    # Format and style
    - gofmt         # Check source code formatting
    - goimports     # Check import order
    - revive        # Check for coding style issues

    # Performance
    - bodyclose    # HTTP response body close

    # Useful
    - errorlint    # Check processed errors
    - nilerr       # Check for errors ignored
    - misspell     # Correct commonly misspelled English words

linters-settings:
  goimports:
    local-prefixes: hasaki.vn

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - singleCaseSwitch

  revive:
    rules:
      - name: duplicated-imports
      - name: confusing-naming
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: package-comments
      - name: receiver-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: time-naming
      - name: nested-structs
      - name: unused-parameter
      - name: function-length
        arguments: [50, 0]
      - name: cognitive-complexity
        arguments: [15]
      - name: cyclomatic
        arguments: [15]
      - name: var-naming

issues:
  # Maximum issues per a linter
  max-issues-per-linter: 500

  # Maximum number of same issues
  max-same-issues: 100

  # Exclude other patterns
  exclude-rules:
    # Remove unused params in test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  # Exclude directories
  exclude-dirs:
    - vendor
    - third_party

# Output configuration
output:
  formats:
    - format: colored-line-number
  print-linter-name: true
  sort-results: true